### ISSUE TITLE
Feature Request: add support for downloading youtube play lists

### ISSUE THREAD

**Issue by ghost** [aliencaocao/ytdlp-gui#1]
trying to download a playlist from youtube and this error gets thrown in :

```
2022-11-20 23:45:09,340 - INFO - YT-DLP GUI (yt-dlp 2022.10.04) (Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)])
2022-11-20 23:45:09,478 - STATUS - Ready

2022-11-20 23:45:14,644 - STATUS - Extracting info
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "yt-dlp-gui.py", line 446, in <lambda>
  File "yt-dlp-gui.py", line 326, in handle_download_info
  File "yt-dlp-gui.py", line 236, in parse_info
KeyError: 'duration_string'
```

here is the playlist in question : [[(https://www.youtube.com/playlist?list=PLKWXuofCqWTDxqnFoqFYRJtSsy0CnxE3R)]](https://www.youtube.com/playlist?list=PLKWXuofCqWTDxqnFoqFYRJtSsy0CnxE3R)

![image](https://user-images.githubusercontent.com/97499891/202967573-5238fb31-134b-48af-9ec5-f96e19156f94.png)

**Comment by aliencaocao** [comment]
Hi, could you please provide the URL you are trying to download? Thanks

**Comment by aliencaocao** [comment]
The app now does not support for downloading playlist, but only videos. You can download any video from that playlist.

**Comment by ghost** [comment]
alright, wasn't sure since the original yt-dlp project does support playlist downloads ?

**Comment by aliencaocao** [comment]
Yes it does but because this GUI is in early development stages so it does not support yet. I will make this a planned feature.

**Comment by ghost** [comment]
i have returned to the country, is there any help you wanted ?

**Comment by aliencaocao** [comment]
Yea sure maybe help with this feature? Im not exactly free this time so things will move slowly in this repo

**Comment by aliencaocao** [comment]
Implemented in https://github.com/aliencaocao/ytdlp-gui/releases/tag/2026.2.4
